# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 28b3e80eedab86a2cadf8ae16d9eb1e7b01102e32570e3c54f103f06d381b759108f61826edbbab855648d9bff6a917f6f0a4fa5633fdd68f692a185d9d1cf11

test:
  secret_key_base: c4609245558268b56ca6fc7a0eb498d1d1ce3fd0252e8cdec58cb9cf9d528d974ac539d96d0f3ad9b695bbf4e2712d61bd83fdf9c3cc51ffa16a9f367bbd5949

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
